server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;

  location ~* ^/(zones|gates|queues|incidents) {
    proxy_pass https://venueflow-backend-806802244785.us-central1.run.app;
    proxy_set_header Host https://venueflow-backend-806802244785.us-central1.run.app;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}